version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Asia/Jakarta

  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    labels:
      - dependencies
    groups:
      dependencies:
        dependency-type: production
        patterns: ['*']
      dev-dependencies:
        dependency-type: development
        patterns: ['*']
